language: shell

os: windows

before_script:
  - wget "http://prdownloads.sourceforge.net/nsis/nsis-3.04-setup.exe?download" -O nsis-setup.exe
  - ./nsis-setup.exe /S
  - wget "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.2/sapmachine-jdk-11.0.2_windows-x64_bin.zip" -O sapmachine.zip
  - 7z.exe x sapmachine.zip
  - move sapmachine-11.0.2 sapmachine
  - dir sapmachine
script:
  - /c/Program Files (x86)/NSIS/makensis.exe /V4 /DVERSION=TEST /DFULLVERSION=ONLY.A.TEST sapmachine.nsi
  - ./sapmachine.exe /S
  