language: shell

- os: windows

before_script:
  - wget "http://prdownloads.sourceforge.net/nsis/nsis-3.04-setup.exe?download" -O nsis-setup.exe
  - ./nsis-setup.exe
script:
  - /c/Program Files (x86)/NSIS/makensis.exe